require 'test_helper'

class Stimulus::Manifest::Test < ActiveSupport::TestCase
  test "generate manifest with multiple file types" do
    manifest = Stimulus::Manifest.generate_from(file_fixture('controllers'))

    refute_includes manifest, '/* eslint-disable */'
    assert_includes manifest, '// This file is auto-generated by ./bin/rails stimulus:manifest:update'
    assert_includes manifest, '// Run that command whenever you add a new controller or create them with'
    assert_includes manifest, '// ./bin/rails generate stimulus controllerName'

    # JavaScript controller
    assert_includes manifest, 'import HelloController from "./hello_controller"'
    assert_includes manifest, 'application.register("hello", HelloController)'

    # CoffeeScript controller
    assert_includes manifest, 'import CoffeeController from "./coffee_controller"'
    assert_includes manifest, 'application.register("coffee", CoffeeController)'

    # TypeScript controller
    assert_includes manifest, 'import TypeScriptController from "./type_script_controller"'
    assert_includes manifest, 'application.register("type-script", TypeScriptController)'

    # Multi words controller using dasherized file name
    assert_includes manifest, 'import MultiWordDashController from "./multi-word-dash_controller"'
    assert_includes manifest, 'application.register("multi-word-dash", MultiWordDashController)'

    # Multi words controller using underscored file name
    assert_includes manifest, 'import MultiWordUnderscoreController from "./multi_word_underscore_controller"'
    assert_includes manifest, 'application.register("multi-word-underscore", MultiWordUnderscoreController)'

    # namespaced controller
    assert_includes manifest, 'import Namespace__NamespacedController from "./namespace/namespaced_controller"'
    assert_includes manifest, 'application.register("namespace--namespaced", Namespace__NamespacedController)'

    # namespaced controller with multiple words using dasherized file name
    assert_includes manifest, 'import Namespace__MultiWordDashController from "./namespace/multi-word-dash_controller"'
    assert_includes manifest, 'application.register("namespace--multi-word-dash", Namespace__MultiWordDashController)'

    # namespaced controller with multiple words using underscored file name
    assert_includes manifest, 'import Namespace__MultiWordUnderscoreController from "./namespace/multi_word_underscore_controller"'
    assert_includes manifest, 'application.register("namespace--multi-word-underscore", Namespace__MultiWordUnderscoreController)'
  end



  class Stimulus::Manifest::Test::Configuration < ActiveSupport::TestCase
    setup do
      StimulusRails.configure do |config|
        config.disable_eslint = true
        config.paths = ["app/javascript/controllers"]
      end
    end

    teardown do
      StimulusRails.configuration = nil
    end

    test "disable_eslint" do
      assert StimulusRails.configuration.disable_eslint
      manifest = Stimulus::Manifest.generate_from(file_fixture('controllers'))
      assert_includes manifest, '/* eslint-disable */'
    end
  end

  # class Stimulus::Manifest::Test::MultiplePaths < ActiveSupport::TestCase
  #   test "generate manifest with multiple file types" do
  #     manifest = Stimulus::Manifest.generate_from([file_fixture('controllers'), file_fixture('components')])

  #     refute_includes manifest, '/* eslint-disable */'
  #     assert_includes manifest, '// This file is auto-generated by ./bin/rails stimulus:manifest:update'
  #     assert_includes manifest, '// Run that command whenever you add a new controller or create them with'
  #     assert_includes manifest, '// ./bin/rails generate stimulus controllerName'

  #     # JavaScript controller
  #     assert_includes manifest, 'import HelloController from "./hello_controller"'
  #     assert_includes manifest, 'application.register("hello", HelloController)'

  #     # CoffeeScript controller
  #     assert_includes manifest, 'import CoffeeController from "./coffee_controller"'
  #     assert_includes manifest, 'application.register("coffee", CoffeeController)'

  #     # TypeScript controller
  #     assert_includes manifest, 'import TypeScriptController from "./type_script_controller"'
  #     assert_includes manifest, 'application.register("type-script", TypeScriptController)'

  #     # Multi words controller using dasherized file name
  #     assert_includes manifest, 'import MultiWordDashController from "./multi-word-dash_controller"'
  #     assert_includes manifest, 'application.register("multi-word-dash", MultiWordDashController)'

  #     # Multi words controller using underscored file name
  #     assert_includes manifest, 'import MultiWordUnderscoreController from "./multi_word_underscore_controller"'
  #     assert_includes manifest, 'application.register("multi-word-underscore", MultiWordUnderscoreController)'

  #     # namespaced controller
  #     assert_includes manifest, 'import Namespace__NamespacedController from "./namespace/namespaced_controller"'
  #     assert_includes manifest, 'application.register("namespace--namespaced", Namespace__NamespacedController)'

  #     # namespaced controller with multiple words using dasherized file name
  #     assert_includes manifest, 'import Namespace__MultiWordDashController from "./namespace/multi-word-dash_controller"'
  #     assert_includes manifest, 'application.register("namespace--multi-word-dash", Namespace__MultiWordDashController)'

  #     # namespaced controller with multiple words using underscored file name
  #     assert_includes manifest, 'import Namespace__MultiWordUnderscoreController from "./namespace/multi_word_underscore_controller"'
  #     assert_includes manifest, 'application.register("namespace--multi-word-underscore", Namespace__MultiWordUnderscoreController)'
  #   end
  # end
end
